language: node_js
os: linux
dist: bionic

env:
  global:
    - IMAGE_NAME=jsloan117/fluentd

notifications:
  email: false

jobs:
  include:
    - stage: build docker images
      services: docker
      before_script: npm install semver
      script: .travis/build-test-push.sh
      cache:
        npm: true
